#!/usr/bin/env node
/**
 * Ensure staging E2E account exists and write newapi-portal/.env.e2e for Playwright.
 */

import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const portalRoot = join(__dirname, "..");
const seedScript = join(__dirname, "seed-screenshot-user.mjs");
const envFile = join(portalRoot, ".env.e2e");

const defaults = {
  E2E_BASE_URL: "https://test.easyapi.work",
  E2E_PORTAL_IDENTIFIER: "scr@qq.com",
  E2E_PORTAL_PASSWORD: "ScreenshotTest123!",
  SEED_EMAIL: "scr@qq.com",
  SEED_PASSWORD: "ScreenshotTest123!",
  SEED_BASE_URL: "https://test.easyapi.work",
};

function mergedEnv(extra = {}) {
  return { ...process.env, ...defaults, ...extra };
}

function runNode(script, env = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [script], {
      cwd: portalRoot,
      stdio: "inherit",
      env: mergedEnv(env),
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve(undefined);
      else reject(new Error(`${script} exited with code ${code}`));
    });
  });
}

function runPnpm(scriptName, env = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn("pnpm", [scriptName], {
      cwd: portalRoot,
      stdio: "inherit",
      env: mergedEnv(env),
      shell: true,
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve(undefined);
      else reject(new Error(`pnpm ${scriptName} exited with code ${code}`));
    });
  });
}

function writeEnvFile(values) {
  const lines = [
    "# Generated by scripts/prepare-e2e-env.mjs — local E2E only (gitignored).",
    `# Updated: ${new Date().toISOString()}`,
    "",
    `E2E_BASE_URL="${values.E2E_BASE_URL}"`,
    `E2E_PORTAL_IDENTIFIER="${values.E2E_PORTAL_IDENTIFIER}"`,
    `E2E_PORTAL_PASSWORD="${values.E2E_PORTAL_PASSWORD}"`,
    `SEED_EMAIL="${values.SEED_EMAIL}"`,
    `SEED_PASSWORD="${values.SEED_PASSWORD}"`,
    `SEED_BASE_URL="${values.SEED_BASE_URL}"`,
    "",
  ];
  writeFileSync(envFile, lines.join("\n"), "utf8");
  console.log(`Wrote ${envFile}`);
}

async function main() {
  const values = {
    E2E_BASE_URL: process.env.E2E_BASE_URL ?? defaults.E2E_BASE_URL,
    E2E_PORTAL_IDENTIFIER:
      process.env.E2E_PORTAL_IDENTIFIER ?? defaults.E2E_PORTAL_IDENTIFIER,
    E2E_PORTAL_PASSWORD:
      process.env.E2E_PORTAL_PASSWORD ?? defaults.E2E_PORTAL_PASSWORD,
    SEED_EMAIL: process.env.SEED_EMAIL ?? defaults.SEED_EMAIL,
    SEED_PASSWORD: process.env.SEED_PASSWORD ?? defaults.SEED_PASSWORD,
    SEED_BASE_URL: process.env.SEED_BASE_URL ?? defaults.SEED_BASE_URL,
  };

  console.log(`Preparing E2E env for ${values.E2E_BASE_URL} ...`);
  await runNode(seedScript, {
    SEED_BASE_URL: values.SEED_BASE_URL,
    SEED_EMAIL: values.SEED_EMAIL,
    SEED_PASSWORD: values.SEED_PASSWORD,
    E2E_PORTAL_PASSWORD: values.E2E_PORTAL_PASSWORD,
  });

  writeEnvFile(values);

  console.log("\nRunning auth setup ...");
  await runPnpm("test:e2e:auth-setup", values);

  console.log("\nDone. Example:");
  console.log(
    "  pnpm exec playwright test tests/e2e/billing-aff.spec.ts --project=authenticated-chromium --workers=1",
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
